#!/usr/bin/ruby
require 'rubygems'
require 'optparse'

require File.join(File.dirname(__FILE__), '../game_server/connection')
require File.join(File.dirname(__FILE__), '../game_server/server')

options = {:port => 5001}

option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: server.rb [options]"

  opts.on("-p", "--port port_number", "Set port number") do |p|
    options[:port] = p
  end
end

option_parser.parse!(ARGV)

Server.new(options).run
